runtime: nodejs20 # Specify your Node.js version
env: standard # Specify that we're using a flexible environment
instance_class: F2 # Choose an instance type, F2 is standard

env_variables:
  GCP_BUCKET_ID : cart-app
  GCP_PROJECT_ID : tag-my-cart-app
  GCP_CLIENT_EMAIL : cart-app-worker@tag-my-cart-app.iam.gserviceaccount.com
  GCP_PRIVATE_KEY : "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC07cvwym6zQNkA\nLpp5AMuRfWmuTcICkGaHmWN+BtX08SZh2ZBS7+23TGxVgqLwyai4z2lqN1FthiD6\nWJrnk9L/35teh/OW8zv+CZkCFyV3yJ+H+UqDSByWXCZhvo8QMNDS50gvnVULSXwb\n54HJHOxYqyA8LyvL+c1GKuIXNPoMQQGZUdIGIaV6BvKl+mAcCxo+dkKlpA5euSBK\nunX8jwGivITfRqUpTseeH4L89aplAEY0YpiRZC75BqMo/j8S1Q2+kOKVnOOD/Px1\njGci74ioJo1WpB0NIH3r0/0ZXYmJNqMHLZVqbh+lop118B1lpoQGQKaWarLxDZxy\nAo0UuIozAgMBAAECggEAArgPXUWpOCYFN+cixk5dVH81B8q+gyb3saOZcKr8yNc2\nJLjX8b8h2K3q6cnomrn8e2QPLiW5XW4cjXQeba1X/ptnO0u30Ilr7ZLUWckxCDl0\nRJpGM7zxRGxt3YqP2NTxIErgzfOb/deMI2zoWEn0fBZVWKSoEH4Ybl3w2BtwDSnC\nTjEZRRKUbvTo+UWmVSQdjVWphgwOzF1PS2RfE49o6w+yaSuzizVBVPwcY6CaUglF\nzN3vceVvUF3P4fIwklMdER3yRhSEQEH1iB7oCxHMiqbZMaaldHSEAUW0dGgcezwz\nkzQzC5RMlXjyfM2mdVhErLsjdx11C4w7XjrLNPOayQKBgQDbvJcd5MUzqYpnYAmv\nwufcAOem0ShywBx4yW3/zWebdzonKVx+USz9aHY8hXWu9mj/6e3CGm8VEk0AITXS\n+QE5hjmxrOM0PU3Lzk/L9dadbQTp+6hKVHTWu82jfxuHPvf2KVk9pyYlgdXH+5ua\nxwFgngljZw17dN9NXbIS7KfaSwKBgQDSyajRialkWT1jr8oFsHKC3+q9iU/uFlTD\nPCoZaEgn39630gSPChIS4yic+y+eIaC0Wr2d5NlBD+5eH0SGFH2kCIe8dsp+dUl2\nbvVNktm8vItrV0Qn5Ea4loWvqPd36vQOFaSSNFIaFypeZTCpeGqmM5a8PGkkTxx3\nNVffJSUeuQKBgFS07sxnVF4GDYSsUQ+gYyE8eBCmsKELze4COJVT6YzU+WX/W9iW\nEnHdwzaxfBxmgTOmSjF5XzkQRP63zrf1pbM3OyZzL2MD/umCLuDBdGpbjHlmuglt\nZV0iKLPOXB5W99+9MNnDhcEPvAnLxMB11uIYCiZ3o4rkEvEQHYWOFWbhAoGATR7v\nH0sIqOhlp5VnitFV9EBMuHAGyItvE8dtd8JJtB0adZLnjBYZKsPl1hmpAGg5TgNt\nINncCwvzIIi8H3pbxapBT1j/GWl8KVLLeUhjVcR+FhXln9rLbTnVS8G8WSmjhYux\nnLR73YPgQo0vUrH2Az0Yx2Iq7dfsCEmCDuiePjECgYEAuqMAuT68oCGRR5uK95Ym\nXvhndN+dNbt0o+bBNs3c+YX64HJ82uF7uGmCXR8VKA6PkepmqUrDjnJAbGRwhuIu\ncEIcQU4JzCdV0eiqwn/EfFJFehkI6Et3sJZjpnqBCVc8+oAljv8/c0yovvfEw0GU\n+GEQ5dxRg3OyziawYhus/VM=\n-----END PRIVATE KEY-----\n"
  MONGODB_URI : mongodb+srv://rattitle:ky1Z3ctgFEWFDJke@cluster0.icepm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0



handlers:
- url: /
  static_files: /client/dist/index.html
  upload: /client/dist/index.html

- url: /static
  static_dir: /client/dist/static

- url: /.*
  static_files: /client/dist/index.html
  upload: /client/dist/index.html
  secure: always